package app

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"time"
)

// ---- process helpers -------------------------------------------------------

func pidAlive(pid int) bool {
	if pid <= 0 {
		return false
	}
	err := syscall.Kill(pid, 0)
	return err == nil || err == syscall.EPERM
}

func portOpen(host string, port int) bool {
	c, err := net.DialTimeout("tcp", net.JoinHostPort(host, strconv.Itoa(port)), 400*time.Millisecond)
	if err != nil {
		return false
	}
	c.Close()
	return true
}

func findLlamaServer() string {
	for _, c := range []string{
		filepath.Join(homeDir, ".local", "bin", "llama-server"),
		"/opt/homebrew/bin/llama-server",
		"/usr/local/bin/llama-server",
	} {
		if st, err := os.Stat(c); err == nil && st.Mode().IsRegular() && st.Mode()&0o111 != 0 {
			return c
		}
	}
	if p, err := exec.LookPath("llama-server"); err == nil {
		return p
	}
	return ""
}

// managedPID returns the recorded pid if that process is still alive.
func managedPID(st State) int {
	if pidAlive(st.PID) {
		return st.PID
	}
	return 0
}

// stopManaged SIGTERMs the managed server, escalating to SIGKILL after wait.
func stopManaged(st *State, wait time.Duration) bool {
	clear := func() {
		st.PID = 0
		saveState(*st)
	}
	if !pidAlive(st.PID) {
		clear()
		return true
	}
	if err := syscall.Kill(st.PID, syscall.SIGTERM); err == syscall.ESRCH {
		clear()
		return true
	}
	deadline := time.Now().Add(wait)
	for time.Now().Before(deadline) {
		if !pidAlive(st.PID) {
			clear()
			return true
		}
		time.Sleep(150 * time.Millisecond)
	}
	_ = syscall.Kill(st.PID, syscall.SIGKILL)
	time.Sleep(200 * time.Millisecond)
	if !pidAlive(st.PID) {
		clear()
		return true
	}
	return false
}

func writeActiveEnv(p Profile) {
	ensureDirs()
	content := fmt.Sprintf(`# Generated by %[1]s — do not edit by hand
# Active profile: %[2]s
# Sourced automatically is optional; prefer: eval "$(%[1]s env)"
export AI_MODE_PROFILE=%[2]s
export AI_MODE_PORT=%[3]d
export AI_MODE_HOST=%[4]s
export AI_MODE_BASE_URL=%[5]s
export OPENAI_BASE_URL=%[5]s
export OPENAI_API_KEY=${OPENAI_API_KEY:-local}
`, appName, p.Name, p.Port, p.Host, p.BaseURL())
	_ = os.WriteFile(activeEnvFile(), []byte(content), 0o644)
}

// startProfile launches llama-server detached in its own session and returns its pid.
func startProfile(p Profile) (int, error) {
	llama := findLlamaServer()
	if llama == "" {
		return 0, fmt.Errorf("llama-server not found on PATH (brew install llama.cpp?)")
	}
	if !isFile(p.Ini) {
		return 0, fmt.Errorf("preset missing: %s", p.Ini)
	}
	if portOpen(p.Host, p.Port) {
		return 0, fmt.Errorf("port %d already in use on %s.\nStop the other process or change port in %s.mode", p.Port, p.Host, p.Name)
	}

	ensureDirs()
	args := []string{
		"--models-preset", p.Ini,
		"--models-max", strconv.Itoa(p.ModelsMax),
		"--host", p.Host,
		"--port", strconv.Itoa(p.Port),
		"--jinja",
	}
	logf, err := os.OpenFile(p.LogFile(), os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return 0, err
	}
	defer logf.Close()
	fmt.Fprintf(logf, "\n===== %s start %s =====\n%s %s\n", appName, nowISO(), llama, strings.Join(args, " "))

	cmd := exec.Command(llama, args...)
	cmd.Stdout = logf
	cmd.Stderr = logf
	cmd.Dir = presetsDir()
	cmd.SysProcAttr = &syscall.SysProcAttr{Setsid: true}
	if err := cmd.Start(); err != nil {
		return 0, err
	}
	pid := cmd.Process.Pid
	_ = cmd.Process.Release()
	return pid, nil
}

func waitHealthy(p Profile, timeout time.Duration) bool {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if _, ok := getJSON(p.BaseURL()+"/models", 1500*time.Millisecond); ok {
			return true
		}
		time.Sleep(400 * time.Millisecond)
	}
	return false
}

// ---- HTTP helpers ----------------------------------------------------------

func getJSON(url string, timeout time.Duration) (map[string]any, bool) {
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return nil, false
	}
	req.Header.Set("User-Agent", appName)
	resp, err := (&http.Client{Timeout: timeout}).Do(req)
	if err != nil {
		return nil, false
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, false
	}
	var out map[string]any
	if json.NewDecoder(resp.Body).Decode(&out) != nil {
		return nil, false
	}
	return out, true
}

func postJSON(url string, body any, timeout time.Duration) (map[string]any, error) {
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", url, bytes.NewReader(payload))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("User-Agent", appName)
	resp, err := (&http.Client{Timeout: timeout}).Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	data, _ := io.ReadAll(resp.Body)
	if resp.StatusCode >= 400 {
		detail := string(data)
		if len(detail) > 500 {
			detail = detail[:500]
		}
		return nil, fmt.Errorf("HTTP %d: %s", resp.StatusCode, detail)
	}
	var out map[string]any
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// ---- tiny JSON navigation --------------------------------------------------

func asMap(v any) map[string]any {
	m, _ := v.(map[string]any)
	return m
}

func asString(v any) string {
	if v == nil {
		return ""
	}
	if s, ok := v.(string); ok {
		return s
	}
	return fmt.Sprint(v)
}

func prettyJSON(v any) string {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	_ = enc.Encode(v)
	return buf.String()
}
